### ISSUE TITLE
uninitialized constant Pry::HOME_RC_FILE when starting arc

### ISSUE THREAD

**Issue by csibug** [appium/ruby_console#104]
Hi, 
I've a problem when starting arc:

This is the traceback:
Traceback (most recent call last):
        15: from C:/Ruby26-x64/bin/arc:23:in `<main>'
        14: from C:/Ruby26-x64/bin/arc:23:in `load'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_console-2.6.0/bin/arc:3:in `<top (required)>'
        12: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_console-2.6.0/lib/cli.rb:10:in `<top (required)>'
         9: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         8: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_console-2.6.0/lib/appium_console.rb:4:in `<top (required)>'
         6: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib-9.18.0/lib/appium_lib.rb:10:in `<top (required)>'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib-9.18.0/lib/appium_lib.rb:10:in `require_relative'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib-9.18.0/lib/appium_lib/appium.rb:8:in `<top (required)>'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib-9.18.0/lib/appium_lib/appium.rb:8:in `require_relative'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib-9.18.0/lib/appium_lib/driver.rb:770:in `<top (required)>': uninitialized constant Pry::HOME_RC_FILE (NameError)

the currently installed gems:

gem list

*** LOCAL GEMS ***

activesupport (6.0.3.2)
addressable (2.7.0, 2.3.8)
appium_console (2.6.0)
appium_lib (10.6.0, 9.18.0)
appium_lib_core (3.10.0, 2.3.4)
archive-zip (0.12.0)
ast (2.4.1)
backports (3.17.0)
bigdecimal (default: 1.4.1)
bond (0.5.1)
builder (3.2.4)
bundler (default: 1.17.2)
capybara (3.33.0, 3.31.0)
capybara-chromedriver-logger (0.3.0)
capybara-screenshot (1.0.24)
childprocess (3.0.0)
chronic_duration (0.10.6)
cmath (default: 1.0.0)
coderay (1.1.3)
colorize (0.8.1)
concurrent-ruby (1.1.6)
csv (default: 3.0.9)
cucumber (4.1.0, 4.0.1, 3.1.2)
cucumber-core (7.1.0, 7.0.0, 3.2.1)
cucumber-create-meta (1.0.0)
cucumber-cucumber-expressions (10.2.2, 10.2.1)
cucumber-expressions (6.0.1)
cucumber-gherkin (14.2.0, 14.0.1, 13.0.0)
cucumber-html-formatter (7.2.0, 7.0.0, 6.0.3)
cucumber-messages (12.4.0, 12.2.0)
cucumber-tag-expressions (2.0.4)
cucumber-tag_expressions (1.1.1)
cucumber-wire (3.1.0, 3.0.0, 0.0.1)
date (default: 2.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0)
diff-lcs (1.3)
e2mmap (default: 0.1.0)
etc (default: 1.0.1)
eventmachine (1.2.7)
faye-websocket (0.10.9)
fcntl (default: 1.0.0)
ffi (1.13.1 x64-mingw32, 1.12.2 x64-mingw32)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
gdbm (default: 2.0.0)
geckodriver-helper (0.24.0)
gherkin (5.1.0)
i18n (1.8.5, 1.8.3)
io-console (default: 0.4.7)
io-like (0.3.1)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
json (default: 2.1.0, 1.8.6)
launchy (2.5.0, 2.4.3)
logger (default: 1.3.0)
matrix (default: 0.1.0)
method_source (1.0.0)
middleware (0.1.0)
mime-types (1.25.1)
mini_mime (1.0.2)
mini_portile2 (2.4.0)
minitest (5.14.1, 5.11.3)
multi_json (1.14.1)
multi_test (0.1.2)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
nokogiri (1.10.10 x64-mingw32, 1.10.9 x64-mingw32)
numerizer (0.1.1)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
parallel (1.19.2)
parser (2.7.1.4)
power_assert (1.1.3)
prime (default: 0.1.0)
protobuf-cucumber (3.10.8)
pry (0.13.1)
psych (default: 3.1.0)
public_suffix (4.0.5)
rack (2.2.3, 2.2.2)
rack-test (1.1.0)
rainbow (3.0.0)
rake (12.3.3)
rdoc (default: 6.1.2)
regexp_parser (1.7.1, 1.7.0)
rest-client (1.6.14)
rexml (default: 3.1.9)
rspec (3.9.0)
rspec-core (3.9.2, 3.9.1)
rspec-expectations (3.9.2, 3.9.1, 3.9.0)
rspec-mocks (3.9.1)
rspec-retry (0.6.2)
rspec-support (3.9.3, 3.9.2)
rss (default: 0.2.7)
rubocop (0.86.0)
rubocop-ast (0.1.0)
ruby-progressbar (1.10.1)
rubyzip (2.3.0, 2.2.0)
rufo (0.12.0)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
selenium-webdriver (3.142.7)
shell (default: 0.7)
spec (5.3.4)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
sys-uname (1.2.1)
test-unit (3.2.9)
thor (1.0.1, 0.20.3)
thread_safe (0.3.6)
thwait (default: 0.1.0)
tomlrb (1.3.0)
tracer (default: 0.1.0)
tzinfo (1.2.7)
unicode-display_width (1.7.0)
unirest (1.1.2)
webrick (default: 1.4.2)
websocket-driver (0.7.3, 0.7.2)
websocket-extensions (0.1.5)
xmlrpc (0.3.0)
xpath (3.2.0)
zeitwerk (2.4.0, 2.3.1)
zlib (default: 1.0.0)

thanks for any help!

**Comment by alvy54** [comment]
Any update on this?

**Comment by KazuCocoa** [comment]
Does this still happen the latest one?
Then, it is appreciated to attach  Ruby, pry and ruby_console versions.
I fixed an issue about pry after 2.6.0 (this issue's version)

**Comment by alvy54** [comment]
Not anymore.  I was using 2.6.0.  Thanks!
