### ISSUE TITLE
Connect to appium server on specific port.

### ISSUE THREAD

**Issue by johnny2k** [appium/ruby_console#34]
I'd like to have two appium servers running. One for launching my tests and one that ARC connects to for making queries and testing commands. Is there a way to specify the port it uses? I tried adding PORT=3453 to the appium.txt file and guessing command-line parameters when starting ARC.

**Comment by juhlila** [comment]
If you came here from a google search, here's how I manage to make it work on different port

`Appium::Driver.new(caps: capabilities, appium_lib: {port: port_number})`

**Comment by JohnOSu** [comment]
@bootstraponline Thanks for the appium.txt sample. 
So, launching appium --port "4725" starts the listener on 0.0.0.0:5500 and arc can find appium using your appium_lib port setting just fine.
However, I'd like to be able to launch appium using an address as well e.g. appium --address 10.22.58.7 --port 4725
Is there an appium.txt setting I can use for this? I tried address, but it doesn't work.

**Comment by bootstraponline** [comment]
maybe `server_url = 10.22.58.7`? 

I don't work on appium anymore. 😭 you could try asking on https://discuss.appium.io/

**Comment by JohnOSu** [comment]
Thanks for the fast response!
I tried server_url = "10.22.58.7" and it gives a 'rescue in merge' : both URI are relative (URI::BadUTIError) so I think I'm getting closer :-) 
I'll try appium.io as you suggest.

**Comment by bootstraponline** [comment]
`custom_url = "http://10.22.58.7:4725/wd/hub"`

maybe ^

**Comment by JohnOSu** [comment]
@bootstraponline Thanks! I tried server_url = "http://10.22.58.7:4725/wd/hub" and that works perfectly.

**Comment by prasanna532** [comment]
appium -a 127.0.0.1 -p 4725

Hope above solution will solve the issue
