### ISSUE TITLE
Prefix pry commands by default

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_console#42]
`Pry.config.command_prefix = "%"`

The command prefix is required otherwise common words such as `reset` will invoke the pry command instead of doing what the user expects.

https://github.com/pry/pry/wiki/Customization-and-configuration#Config_prefix

**Comment by xsmaster** [comment]
Not sure why this is a  bug. when doing a %cd variable works fine for me. Please advise.

**Comment by bootstraponline** [comment]
I fixed this last year and forgot to close the issue.

- https://github.com/appium/ruby_console/commit/de03ad68363c6c33348c95369c90dbd036f37c18

**Comment by xsmaster** [comment]
Thanks @bootstraponline
