### ISSUE TITLE
Commandline args

### ISSUE THREAD

**Issue by xsmaster** [appium/ruby_console#43]
It would be killer to pass in a path to the appium.txt file. :)

**Comment by bootstraponline** [comment]
I agree. blocked on https://github.com/appium/ruby_lib/issues/280

we should allow loading arbitrary appium.txt files regardless of path or name.

**Comment by xsmaster** [comment]
wow it seems it might be awhile...

**Comment by bootstraponline** [comment]
pull requests are welcome :smile: I review them quickly.

**Comment by xsmaster** [comment]
I will see what I can do. I'm learning ruby on a daily basis.

**Comment by mlainez** [comment]
Hi, I've submitted pull request #51 to allow specifying a custom appium.txt directory. Not changing the "appium.txt" name, just specifying a directory to look in. Let me know if you have any feedback.

**Comment by mlainez** [comment]
@xsmaster #51 was recently merged and allows you to specify an appium.txt file with the toml command. Check the updated documentation.
