### ISSUE TITLE
ARC - Dependencies

### ISSUE THREAD

**Issue by xsmaster** [appium/ruby_console#45]
It seems the version of Pry is very out of date. Does anyone mind if we upgrade it? I was trying to cd into an object and it failed. :(

So I will see what I can do and have someone else review it.

**Comment by bootstraponline** [comment]
I agree it should be updated. Update the gemspec to the new version on rubygems then see if anything breaks. If it's all set then a pull request can be merged.

**Comment by bootstraponline** [comment]
dupe of https://github.com/appium/ruby_console/issues/40, let's track the issue there.

**Comment by bootstraponline** [comment]
@xsmaster v1.0.4 [has been released to rubygems](https://rubygems.org/gems/appium_console)
