### ISSUE TITLE
ARC Wiki

### ISSUE THREAD

**Issue by xsmaster** [appium/ruby_console#48]
Not sure if anyone else like this or not. But it would be killer to have some doc or Wiki pages on useful commands. 

Thoughts?

**Comment by bootstraponline** [comment]
All the commands are here (arc commands are the same as appium/ruby_lib):

- [ios docs](https://github.com/appium/ruby_lib/blob/master/docs/ios_docs.md)
- [android docs](https://github.com/appium/ruby_lib/blob/master/docs/android_docs.md)

In terms of the useful commands, there's the [bootcamp guide](http://sauceio.com/index.php/tag/appium-bootcamp/). Is there anything else I'm missing?

**Comment by bootstraponline** [comment]
I enabled the wiki: https://github.com/appium/ruby_console/wiki
