### ISSUE TITLE
Bundle console doesn't work unless we add  require => false in Gemfile

### ISSUE THREAD

**Issue by kowal** [appium/ruby_console#49]
Hi

Given Gemfile:

```
gem 'appium_console'
gem 'appium_lib'
gem 'appium_capybara'
```

When I run `bundle console` I get:

``` bash
RuntimeError: toml doesn't exist /home/kowal/my_project/appium.txt
../gems/appium_lib-7.0.0/lib/appium_lib/driver.rb:85:in `load_appium_txt'
../gems/appium_console-1.0.4/lib/appium_console.rb:14:in `block in <top (required)>'
../gems/appium_console-1.0.4/lib/appium_console.rb:37:in `<module:Console>'
../gems/appium_console-1.0.4/lib/appium_console.rb:31:in `<module:Appium>'
../gems/appium_console-1.0.4/lib/appium_console.rb:30:in `<top (required)>'
../gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
```

This is fixed by `gem 'appium_console', :require => false` but I'm not sure if this is what we want. Maybe it could be fixed that it is not required to change Gemfille entry and make bundle console work.

Any ideas?

**Comment by bootstraponline** [comment]
The appium ruby console requires an appium.txt file to start a session. See [this example](https://github.com/appium/ruby_lib/blob/master/android_tests/appium.txt).

I think require false is correct if you want to use bundle_console without starting an appium console session.
