### ISSUE TITLE
arc doesn't release appium session when exiting

### ISSUE THREAD

**Issue by mlainez** [appium/ruby_console#53]
Don't know if it's the same for everyone but arc doesn't release the appium session once you leave the console. It means you have to kill appium and restart it to restart arc or execute test scripts.

**Comment by bootstraponline** [comment]
are you ending the the session with `x`?

**Comment by mlainez** [comment]
Nope, just with ctrl-d

It works indeed with x but is it possible to hook to pry before it quits and make it work with ctrl-d ?

**Comment by bootstraponline** [comment]
probably, never tried

**Comment by bootstraponline** [comment]
https://github.com/pry/pry/wiki/Hooks#Hooks_after_session_event looks promising.
