### ISSUE TITLE
Tomlrb::ParseError when running `arc`

### ISSUE THREAD

**Issue by TheChell** [appium/ruby_console#56]
Hi,

I'm trying to get setup with Appium and have the following set:

**rbenv version:** 2.3.0 (set by Users/name/.rbenv/version)
**arc version**
     **appium_console:** v2.0.1
     **appium_lib:** v8.0.2

I can provide a full gem list if desired.

My appium.txt file is as follows

`[caps]`
`platformName = "iOS"`
`platformVersion = "8.0.2"`
`app = "~/Users/name/Downloads/ios.ipa"`
`deviceName = "iPhone"`
`udid = "ad6d2c2d9dc9f63a7ffae9210c8ac17be4f9402c"`
`bundleId = 'com.Company.iPhoneEnterprise'``

When I run `arc` or `bundle exec arc` I'm seeing the error:

```
`bundler: failed to load command: arc (/Users/name/.rbenv/versions/2.3.0/bin/arc)
Tomlrb::ParseError:
parse error on value ":" (error)
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tomlrb-1.2.1/lib/tomlrb.rb:25:in `rescue in parse'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tomlrb-1.2.1/lib/tomlrb.rb:22:in `parse'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tomlrb-1.2.1/lib/tomlrb.rb:38:in `load_file'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/appium_lib-8.0.2/lib/appium_lib/driver.rb:89:in `load_appium_txt'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/appium_console-2.0.1/lib/appium_console.rb:19:in `block in setup'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/appium_console-2.0.1/lib/appium_console.rb:41:in `start'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/appium_console-2.0.1/lib/cli.rb:71:in `init'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/appium_console-2.0.1/lib/cli.rb:80:in `<top (required)>'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/appium_console-2.0.1/bin/arc:3:in `require'
  /Users/name/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/appium_console-2.0.1/bin/arc:3:in `<top (required)>'
  /Users/name/.rbenv/versions/2.3.0/bin/arc:23:in `load'
  /Users/name/.rbenv/versions/2.3.0/bin/arc:23:in `<top (required)>'`
```

I've updated all my gems and am not sure what the cause of this issue could be. My apologies if this is only an issue on my end. I'd appreciate any help.

**Comment by bootstraponline** [comment]
In your unredacted appium.txt, is there a `:` somewhere?

**Comment by bootstraponline** [comment]
also try `gem uninstall -aIx tomlrb; gem install tomlrb -v 1.2.1`

**Comment by TheChell** [comment]
I should have prefaced that - no there is no `:` in my appium.txt file. I also tried uninstalling and reinstalling the` v 1.2.1` of tomlrb, but still see the same error :(

**Comment by bootstraponline** [comment]
If you email me the full appium.txt I'll try to replicate the error & fix the problem. The `arc` tool is working fine for me so I'm not sure why the toml parser is crashing. I've listed my contact info in [my github profile.](https://github.com/bootstraponline)

**Comment by TheChell** [comment]
Thank you for the quick response. It was user error - I had the appium.txt file in 2 places and had a `:` in the folder I was calling `arc` from.

**Comment by amaxsilva** [comment]
I have this following error and I can't solve it.

C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/appium_lib-9.18.0/lib/appium_lib/driver.rb:770:in `<top (required)>': uninitialized constant Pry::HOME_RC_FILE (NameError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/appium_lib-9.18.0/lib/appium_lib/appium.rb:8:in `require_relative'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/appium_lib-9.18.0/lib/appium_lib/appium.rb:8:in `<top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/appium_lib-9.18.0/lib/appium_lib.rb:10:in `require_relative'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/appium_lib-9.18.0/lib/appium_lib.rb:10:in `<top (required)>'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/appium_console-2.6.0/lib/appium_console.rb:4:in `<top (required)>'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/appium_console-2.6.0/lib/cli.rb:10:in `<top (required)>'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/appium_console-2.6.0/bin/arc:3:in `<top (required)>'
        from C:/Ruby30-x64/bin/arc:23:in `load'
        from C:/Ruby30-x64/bin/arc:23:in `<main>'
