### ISSUE TITLE
release 2.1.0

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_console#61]
- [x] arc setup ios fails #57
    - https://github.com/appium/ruby_console/pull/59/files
- [x] get permission to release this gem to rubygem

**Comment by KazuCocoa** [comment]
using https://github.com/appium/appium_thor .

**Comment by nonkor** [comment]
Hey @KazuCocoa! May you clarify a current status of the release? I started to work with arc and found the fix is still wasn't delivered with a new version. Any way to bump it?

**Comment by KazuCocoa** [comment]
Thanks!
I just forgot to publish this gem.
I should get permission.

**Comment by KazuCocoa** [comment]
@bootstraponline @titusfortner 
Could you add me to https://rubygems.org/gems/appium_console to be able to publish this library?

I've attached my email address in https://github.com/appium/ruby_lib/issues/391#issuecomment-26129058 .

**Comment by bootstraponline** [comment]
Done

**Comment by KazuCocoa** [comment]
@nonkor I just published. Could you check it?

https://rubygems.org/gems/appium_console/versions/2.1.0

**Comment by bootstraponline** [comment]
looks like the date is wrong?

> 2.1.0 - September 23, 2016 (217 KB)

and there's no release tag. There's a thor publish command which automates the process. `thor bump` then `thor publish`

**Comment by KazuCocoa** [comment]
oops, I'll check.

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_console/pull/59/files is the latest commit.
According to this commit, release data is `2016-09-23`. So, the date is correct, I think.

BTW, I should push release tag. I'll do it.

**Comment by bootstraponline** [comment]
the [date is usually the date the release is pushed to rubygems](https://github.com/appium/appium_thor/blob/master/lib/appium_thor/helpers.rb#L74). not a big deal either way.

**Comment by nonkor** [comment]
@KazuCocoa it works, awesome!
