### ISSUE TITLE
iOSNsPredicateString is not working

### ISSUE THREAD

**Issue by vikramvi** [appium/ruby_console#72]
I'm using xpath to find mobile element as below

`
@driver.find_element(:xpath, "//XCUIElementTypeButton[contains(@label,'Create a site')]")
`

This works fine, but when I want to use predicate instead like below it doesn't work

```
@driver.find_element(:MobileBy.iOSNsPredicateString, "type=='XCUIElementTypeButton' AND label=='Create a site'")
NoMethodError: undefined method `iOSNsPredicateString' for :MobileBy:Symbol
```

Please clarify if this is bug or I'm using it wrongly ?

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib/blob/209fb3fce4f2e567c6d6ba2395eec9b98669d02d/docs/ios_docs.md#ios_predicate_string_find-ios

`ruby_lib` doesn't have `:MobileBy.iOSNsPredicateString`.
`ruby_lib` works with `@driver.find_element(:predicate, "predicate string")`

**Comment by KazuCocoa** [comment]
^ @vikramvi

**Comment by vikramvi** [comment]
@KazuCocoa  Thanks a ton for your help. 

got it working as below

> @driver.find_element(:predicate,"label=='Create a site'")

Closing the issue.
