### ISSUE TITLE
Broken Link : bootcamp guide on the ruby console.

### ISSUE THREAD

**Issue by vikramvi** [appium/ruby_console#73]
Please fix the broken link "bootcamp guide on the ruby console."

Thanks,
Vikram

**Comment by KazuCocoa** [comment]
https://wiki.saucelabs.com/display/DOCS/Appium+Bootcamp+by+Dave+Haeffner+and+Matthew+Edwards is new one...?

**Comment by vikramvi** [comment]
Thanks again @KazuCocoa 

Regards,
Vikram
