### ISSUE TITLE
confusing warning message "[DEPRECATION] Appium::Driver.new(opts) will not generate global driver by defaul"

### ISSUE THREAD

**Issue by vikramvi** [appium/ruby_console#76]
appium_console (2.4.0)
appium_lib (9.6.1)

I use `arc` to explore app and find out elements, with latest version I saw this message 

`[DEPRECATION] Appium::Driver.new(opts) will not generate global driver by default.If you would like to generate the global driver dy default, please initialise driver with Appium::Driver.new(opts, true)`

am not sure how this will affect existing functionality ?  please clarify 

once `arc` session is successfully started; I make use of commands 
```
@driver.page
@driver.find_element etc
```
In which case does 
`Appium::Driver.new(opts, true)` is needed ?

**Comment by KazuCocoa** [comment]
thanks!

`appium_lib` define `$driver` by default, but I'd like to skip it to be able to available thread programming for multiple iOS simulator tests.
To continue to use `$driver`, we need to set `Appium::Driver.new(opts, true)`.
I should have updated the following. I'll update here soon. thanks!
https://github.com/appium/ruby_console/blob/master/lib/start.rb#L16

**Comment by KazuCocoa** [comment]
https://rubygems.org/gems/appium_console/versions/2.5.0

**Comment by vikramvi** [comment]
After updating gem, the warning message is not visible anymore

@KazuCocoa can you please clarify in detail may be in README section

1.  how to use `Appium::Driver.new(opts, true)`, as of today I start appium server in terminal, another tab start `arc` to inspect application ?  Please explain in detail

2.  how to use `$driver`  for multiple iOS simulator tests ? Are you talking about XCode 9 support for multiple simulators ?

It will be nice to have these covered in detailed within README section.

Thanks in advance.

**Comment by vikramvi** [comment]
@KazuCocoa  can you please keep the ticket in open state till README is updated ? As it'll be easier to track.

**Comment by KazuCocoa** [comment]
@vikramvi 

> 1.

If you can do

> as of today I start appium server in terminal, another tab start arc to inspect application ?

 with less than or equal to `ruby_lib 9.6.0`, you can do the same thing with `Appium::Driver.new(opts, true)`.

> 2.

If you mean [run test on multiple simulators with Xcode9](https://github.com/appium/ruby_lib/blob/master/docs/ios_xcuitest.md#run-tests-on-multiple-simulators-with-xcode-9) and you'd like to handle `$driver` with thread programming, you can't use `$driver` since `$driver` is shared between threads and it can't multiple session in one driver instance.

> in README section

I've already updated `Appium::Driver.new(opts, true/false)` in each documentations mentioned about `Appium::Driver.new()` and multiple simulators in Xcode9 section I attached the above in ruby_lib repository.
Also, I've created https://github.com/appium/ruby_lib/issues/657 to update readme and the other documentations as our future work.

**Comment by vikramvi** [comment]
@KazuCocoa  Arigatou Gozaimasu

**Comment by Harsh-Mindtree** [comment]
Can any one please help me on where should i add "true" parameter, when i am initializing Appium driver using Capybara

Code i am using currently - 

Capybara.register_driver(:appium) do |app|
    appium_lib_options = { server_url:           url}
    all_options = {appium_lib:  appium_lib_options, caps:        desired_caps_ios }
    Appium::Capybara::Driver.new app, all_options
end
Capybara.default_driver = :appium

**Comment by KazuCocoa** [comment]
@Harsh-Mindtree Thanks the report!
I found `ruby_lib` should change the way to initialise for capybara's case.
I'll merge and release.

After release, I'll mention you again.

**Comment by Harsh-Mindtree** [comment]
Thanks alot KazuCocoa:), will be looking forward to get the next release, meanwhile if someone is facing the same problem we can edit driver.rb in appium_capybara lib. Change "@appium_driver = Appium::Driver.new @options, false" to "@appium_driver = Appium::Driver.new @options, true" and your code will work again but only locally for now.

**Comment by Harsh-Mindtree** [comment]
Hi @KazuCocoa 

I tried initializing appium capybara this way -

Capybara.register_driver(:appium) do |app|
appium_lib_options = { server_url: url}
all_options = {appium_lib: appium_lib_options,global_driver: true, caps: desired_caps_ios }
Appium::Capybara::Driver.new app, all_options
end
Capybara.default_driver = :appium

But the global driver is still not working. Could you please help me if i am initializing it in wrong way?

Gem versions using:-
 appium_capybara 1.4.1
appium_lib 9.8.1

**Comment by KazuCocoa** [comment]
The following will help you? @Harsh-Mindtree 

https://github.com/appium/appium_capybara/compare/master...KazuCocoa:global-driver-example?expand=1
