### ISSUE TITLE
uninitialized constant #<Class:Appium::Console>::AwesomePrint (NameError)

### ISSUE THREAD

**Issue by DewaldSchoonderwoerd** [appium/ruby_console#87]
Recently updated my gems and started receiving this error.

Console:
/home/dewald/.rvm/gems/ruby-2.4.0/gems/appium_console-2.7.2/lib/appium_console.rb:37:in `start': uninitialized constant #<Class:Appium::Console>::AwesomePrint (NameError)
	from /home/dewald/.rvm/gems/ruby-2.4.0/gems/appium_console-2.7.2/lib/cli.rb:77:in `init'
	from /home/dewald/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/dewald/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/dewald/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/dewald/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /home/dewald/.rvm/gems/ruby-2.4.0/gems/appium_console-2.7.2/lib/cli.rb:86:in `<top (required)>'
	from /home/dewald/.rvm/gems/ruby-2.4.0/gems/appium_console-2.7.2/bin/arc:3:in `require'
	from /home/dewald/.rvm/gems/ruby-2.4.0/gems/appium_console-2.7.2/bin/arc:3:in `<top (required)>'
	from /home/dewald/.rvm/gems/ruby-2.4.0/bin/arc:22:in `load'
	from /home/dewald/.rvm/gems/ruby-2.4.0/bin/arc:22:in `<main>'
	from /home/dewald/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/dewald/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

appium.txt:
[caps]
platformName = "Android"
deviceName = "Nexus 5X"
noReset = "true"
app = "app_folder/staging/latest/link_android_qa_1086.apk"
appPackage = "com.ttrumpet.qa"
appActivity = "com.ttrumpet.sa.SplashScreen"
autoLaunch = "True"
autoGrantPermissions = "true"

**Comment by KazuCocoa** [comment]
Thanks for the report and sorry for my regression.
The reason is my refactoring for `ruby_lib`. I'll release the new version soon. thanks.

**Comment by KazuCocoa** [comment]
@DewaldSchoonderwoerd 
https://rubygems.org/gems/appium_console/versions/2.8.0
