### ISSUE TITLE
Ability to require files in in arc session

### ISSUE THREAD

**Issue by CoryWritesCode** [appium/ruby_console#93]
Hey there! I was wondering if there was any existing support for `require`/`require relative` files in an `arc` session. If not would it be too much trouble to get that as a feature?

Let me know! Thanks!

**Comment by KazuCocoa** [comment]
Do you mean below case?

```
$ bundle exec arc toml appium.txt
[1] pry(main)> require 'rexml/document'  # You'd like to require 'rexml/document' additionally
true
```

You can call `load` as well since the console is `pry`. You can require/load items following Ruby syntax rule.

**Comment by CoryWritesCode** [comment]
yes. every time I enter the correct path to the file or directory I get an error
![image](https://user-images.githubusercontent.com/34924300/47867356-46c3b580-ddcf-11e8-971f-881dab523c97.png)

**Comment by CoryWritesCode** [comment]
I have since been able to `load` the file but not able to `require` it with a full path
![screen shot 2018-11-01 at 12 30 52 pm](https://user-images.githubusercontent.com/34924300/47868421-234e3a00-ddd2-11e8-910d-010331f4252b.png)

**Comment by CoryWritesCode** [comment]
even when doing that, calling methods on the `base_page.rb`doesn't work.

**Comment by KazuCocoa** [comment]
What about the absolute path in the `./rakefile` case? or use `require_relevant`?

`require` doesn't need `.rb`. The difference between from load and require is below.
https://stackoverflow.com/questions/3170638/how-does-load-differ-from-require-in-ruby

> even when doing that, calling methods on the base_page.rbdoesn't work.

I'm not sure your code, but after the require/load, it should work as Ruby code.
Can you call the method via vanila `pry` console?

close since this is Ruby code thing. (not ruby_console)

**Comment by CoryWritesCode** [comment]
Okay, so sorry it took me so long to get back to you.
I was able to `require` by dropping the `.rb` from the Base Page.
![screen shot 2018-11-06 at 7 53 54 am](https://user-images.githubusercontent.com/34924300/48068940-beac2a00-e199-11e8-9ce3-d77b768f5f4a.png)

But it's still not letting me use the custom methods we have in the `BasePage` class
![screen shot 2018-11-06 at 7 54 07 am](https://user-images.githubusercontent.com/34924300/48068996-e3a09d00-e199-11e8-9728-a8540d1c962b.png)

**Comment by KazuCocoa** [comment]
> All I needed to do was create a new instance of the class I was using where the methods were.

👍 
Definitely. You need to create a new instance to enable required stuff in vanilla `class`
