### ISSUE TITLE
'XCUITest requires Appium version >= 1.6.0' error is shown with Appium 1.10.0

### ISSUE THREAD

**Issue by wrathtodd** [appium/ruby_console#94]
After upgrade to the latest Appium version it's not possible to launch Appium ruby console because of the 'XCUITest requires Appium version >= 1.6.0' error (which is solved by updating to 9.16.1 appium_lib gem for Cucumber, but for the console it's still reproducible). 

Preconditions:
- Appium 1.10.0
- appium_console 2.9.1
- Xcode 10.1
- Real device, iPhone 7, iOS 12.1

Steps to reproduce:

1. Launch appium server by '**appium &**'
2. Launch appium ruby console by '**arc**'

**Actual result:** The 'XCUITest requires Appium version >= 1.6.0'  error is shown

**Comment by KazuCocoa** [comment]
thanks, ah, sorry for missing the update for this library. Will do soon

**Comment by KazuCocoa** [comment]
https://rubygems.org/gems/appium_console/versions/2.9.2
